// Code generated by protoc-gen-go-enum. DO NOT EDIT.
// source: domain/book/meta/book.proto

package meta

// 配置状态
const (
	FLOW_STATUS_STOP int64 = 0 //未启用、停用
	FLOW_STATUS_OK   int64 = 1 //启用
)

var (
	FLOW_STATUS_TXT = map[int64]string{
		FLOW_STATUS_STOP: "未启用、停用",
		FLOW_STATUS_OK:   "启用",
	}
)

// 书籍形式  FORMAT
const (
	FORMAT_FORMAT_FEEDS_AD        int64 = 1 //信息流
	FORMAT_FORMAT_SPLASH_AD       int64 = 2 //开屏
	FORMAT_FORMAT_REWARD_VIDEO_AD int64 = 3 //激励视频
	FORMAT_FORMAT_BANNER_AD       int64 = 4 //Banner
	FORMAT_FORMAT_PRE_ROLL_AD     int64 = 5 //前贴
	FORMAT_FORMAT_INTERSTITIAL_AD int64 = 6 //插屏
	FORMAT_FORMAT_FLOAT_AD        int64 = 7 //浮层
)

var (
	FORMAT_TXT = map[int64]string{
		FORMAT_FORMAT_FEEDS_AD:        "信息流",
		FORMAT_FORMAT_SPLASH_AD:       "开屏",
		FORMAT_FORMAT_REWARD_VIDEO_AD: "激励视频",
		FORMAT_FORMAT_BANNER_AD:       "Banner",
		FORMAT_FORMAT_PRE_ROLL_AD:     "前贴",
		FORMAT_FORMAT_INTERSTITIAL_AD: "插屏",
		FORMAT_FORMAT_FLOAT_AD:        "浮层",
	}
)
