// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: article/article.proto

package article

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetImageUploadURLRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetImageUploadURLRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetImageUploadURLRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetImageUploadURLRequestMultiError, or nil if none found.
func (m *GetImageUploadURLRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetImageUploadURLRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetFileExt()); l < 1 || l > 10 {
		err := GetImageUploadURLRequestValidationError{
			field:  "FileExt",
			reason: "value length must be between 1 and 10 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetImageUploadURLRequestMultiError(errors)
	}

	return nil
}

// GetImageUploadURLRequestMultiError is an error wrapping multiple validation
// errors returned by GetImageUploadURLRequest.ValidateAll() if the designated
// constraints aren't met.
type GetImageUploadURLRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetImageUploadURLRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetImageUploadURLRequestMultiError) AllErrors() []error { return m }

// GetImageUploadURLRequestValidationError is the validation error returned by
// GetImageUploadURLRequest.Validate if the designated constraints aren't met.
type GetImageUploadURLRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetImageUploadURLRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetImageUploadURLRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetImageUploadURLRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetImageUploadURLRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetImageUploadURLRequestValidationError) ErrorName() string {
	return "GetImageUploadURLRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetImageUploadURLRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetImageUploadURLRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetImageUploadURLRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetImageUploadURLRequestValidationError{}

// Validate checks the field values on ImageUploadURLReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ImageUploadURLReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImageUploadURLReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ImageUploadURLReplyMultiError, or nil if none found.
func (m *ImageUploadURLReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ImageUploadURLReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ImageId

	// no validation rules for UploadUrl

	// no validation rules for Url

	if len(errors) > 0 {
		return ImageUploadURLReplyMultiError(errors)
	}

	return nil
}

// ImageUploadURLReplyMultiError is an error wrapping multiple validation
// errors returned by ImageUploadURLReply.ValidateAll() if the designated
// constraints aren't met.
type ImageUploadURLReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImageUploadURLReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImageUploadURLReplyMultiError) AllErrors() []error { return m }

// ImageUploadURLReplyValidationError is the validation error returned by
// ImageUploadURLReply.Validate if the designated constraints aren't met.
type ImageUploadURLReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImageUploadURLReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImageUploadURLReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImageUploadURLReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImageUploadURLReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImageUploadURLReplyValidationError) ErrorName() string {
	return "ImageUploadURLReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ImageUploadURLReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImageUploadURLReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImageUploadURLReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImageUploadURLReplyValidationError{}

// Validate checks the field values on CreateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateArticleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateArticleRequestMultiError, or nil if none found.
func (m *CreateArticleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateArticleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 255 {
		err := CreateArticleRequestValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetContent()) < 1 {
		err := CreateArticleRequestValidationError{
			field:  "Content",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateArticleRequest_Status_InLookup[m.GetStatus()]; !ok {
		err := CreateArticleRequestValidationError{
			field:  "Status",
			reason: "value must be in list [0 2 3]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateArticleRequestMultiError(errors)
	}

	return nil
}

// CreateArticleRequestMultiError is an error wrapping multiple validation
// errors returned by CreateArticleRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateArticleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateArticleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateArticleRequestMultiError) AllErrors() []error { return m }

// CreateArticleRequestValidationError is the validation error returned by
// CreateArticleRequest.Validate if the designated constraints aren't met.
type CreateArticleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateArticleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateArticleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateArticleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateArticleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateArticleRequestValidationError) ErrorName() string {
	return "CreateArticleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateArticleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateArticleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateArticleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateArticleRequestValidationError{}

var _CreateArticleRequest_Status_InLookup = map[int32]struct{}{
	0: {},
	2: {},
	3: {},
}

// Validate checks the field values on EmptyReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EmptyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmptyReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmptyReplyMultiError, or
// nil if none found.
func (m *EmptyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *EmptyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EmptyReplyMultiError(errors)
	}

	return nil
}

// EmptyReplyMultiError is an error wrapping multiple validation errors
// returned by EmptyReply.ValidateAll() if the designated constraints aren't met.
type EmptyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmptyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmptyReplyMultiError) AllErrors() []error { return m }

// EmptyReplyValidationError is the validation error returned by
// EmptyReply.Validate if the designated constraints aren't met.
type EmptyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmptyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmptyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmptyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmptyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmptyReplyValidationError) ErrorName() string { return "EmptyReplyValidationError" }

// Error satisfies the builtin error interface
func (e EmptyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmptyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmptyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmptyReplyValidationError{}

// Validate checks the field values on GetMyArticleDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMyArticleDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMyArticleDetailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMyArticleDetailRequestMultiError, or nil if none found.
func (m *GetMyArticleDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMyArticleDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetMyArticleDetailRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetMyArticleDetailRequestMultiError(errors)
	}

	return nil
}

// GetMyArticleDetailRequestMultiError is an error wrapping multiple validation
// errors returned by GetMyArticleDetailRequest.ValidateAll() if the
// designated constraints aren't met.
type GetMyArticleDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMyArticleDetailRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMyArticleDetailRequestMultiError) AllErrors() []error { return m }

// GetMyArticleDetailRequestValidationError is the validation error returned by
// GetMyArticleDetailRequest.Validate if the designated constraints aren't met.
type GetMyArticleDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMyArticleDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMyArticleDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMyArticleDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMyArticleDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMyArticleDetailRequestValidationError) ErrorName() string {
	return "GetMyArticleDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMyArticleDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMyArticleDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMyArticleDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMyArticleDetailRequestValidationError{}

// Validate checks the field values on UpdateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateArticleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateArticleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateArticleRequestMultiError, or nil if none found.
func (m *UpdateArticleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateArticleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateArticleRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 255 {
		err := UpdateArticleRequestValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetContent()) < 1 {
		err := UpdateArticleRequestValidationError{
			field:  "Content",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _UpdateArticleRequest_Status_InLookup[m.GetStatus()]; !ok {
		err := UpdateArticleRequestValidationError{
			field:  "Status",
			reason: "value must be in list [0 2 3]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateArticleRequestMultiError(errors)
	}

	return nil
}

// UpdateArticleRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateArticleRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateArticleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateArticleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateArticleRequestMultiError) AllErrors() []error { return m }

// UpdateArticleRequestValidationError is the validation error returned by
// UpdateArticleRequest.Validate if the designated constraints aren't met.
type UpdateArticleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateArticleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateArticleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateArticleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateArticleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateArticleRequestValidationError) ErrorName() string {
	return "UpdateArticleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateArticleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateArticleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateArticleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateArticleRequestValidationError{}

var _UpdateArticleRequest_Status_InLookup = map[int32]struct{}{
	0: {},
	2: {},
	3: {},
}

// Validate checks the field values on ArticleIDRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ArticleIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArticleIDRequestMultiError, or nil if none found.
func (m *ArticleIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ArticleIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ArticleIDRequestMultiError(errors)
	}

	return nil
}

// ArticleIDRequestMultiError is an error wrapping multiple validation errors
// returned by ArticleIDRequest.ValidateAll() if the designated constraints
// aren't met.
type ArticleIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleIDRequestMultiError) AllErrors() []error { return m }

// ArticleIDRequestValidationError is the validation error returned by
// ArticleIDRequest.Validate if the designated constraints aren't met.
type ArticleIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleIDRequestValidationError) ErrorName() string { return "ArticleIDRequestValidationError" }

// Error satisfies the builtin error interface
func (e ArticleIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleIDRequestValidationError{}

// Validate checks the field values on ArticleDetailReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ArticleDetailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleDetailReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArticleDetailReplyMultiError, or nil if none found.
func (m *ArticleDetailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleDetailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Status

	// no validation rules for AuthorNick

	// no validation rules for AuthorAvatar

	// no validation rules for Ip

	// no validation rules for CreatedTime

	// no validation rules for UpdatedTime

	// no validation rules for IsLiked

	// no validation rules for LikeCount

	for idx, item := range m.GetImages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ArticleDetailReplyValidationError{
						field:  fmt.Sprintf("Images[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ArticleDetailReplyValidationError{
						field:  fmt.Sprintf("Images[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ArticleDetailReplyValidationError{
					field:  fmt.Sprintf("Images[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ArticleDetailReplyMultiError(errors)
	}

	return nil
}

// ArticleDetailReplyMultiError is an error wrapping multiple validation errors
// returned by ArticleDetailReply.ValidateAll() if the designated constraints
// aren't met.
type ArticleDetailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleDetailReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleDetailReplyMultiError) AllErrors() []error { return m }

// ArticleDetailReplyValidationError is the validation error returned by
// ArticleDetailReply.Validate if the designated constraints aren't met.
type ArticleDetailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleDetailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleDetailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleDetailReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleDetailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleDetailReplyValidationError) ErrorName() string {
	return "ArticleDetailReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ArticleDetailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleDetailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleDetailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleDetailReplyValidationError{}

// Validate checks the field values on ArticleImage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ArticleImage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleImage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArticleImageMultiError, or
// nil if none found.
func (m *ArticleImage) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleImage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Url

	if len(errors) > 0 {
		return ArticleImageMultiError(errors)
	}

	return nil
}

// ArticleImageMultiError is an error wrapping multiple validation errors
// returned by ArticleImage.ValidateAll() if the designated constraints aren't met.
type ArticleImageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleImageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleImageMultiError) AllErrors() []error { return m }

// ArticleImageValidationError is the validation error returned by
// ArticleImage.Validate if the designated constraints aren't met.
type ArticleImageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleImageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleImageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleImageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleImageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleImageValidationError) ErrorName() string { return "ArticleImageValidationError" }

// Error satisfies the builtin error interface
func (e ArticleImageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleImage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleImageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleImageValidationError{}
