// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: article/article.proto

package article

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetImageUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileExt       string                 `protobuf:"bytes,1,opt,name=file_ext,json=fileExt,proto3" json:"file_ext"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageUploadURLRequest) Reset() {
	*x = GetImageUploadURLRequest{}
	mi := &file_article_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageUploadURLRequest) ProtoMessage() {}

func (x *GetImageUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetImageUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{0}
}

func (x *GetImageUploadURLRequest) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

type ImageUploadURLReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       uint64                 `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUploadURLReply) Reset() {
	*x = ImageUploadURLReply{}
	mi := &file_article_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUploadURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadURLReply) ProtoMessage() {}

func (x *ImageUploadURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadURLReply.ProtoReflect.Descriptor instead.
func (*ImageUploadURLReply) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{1}
}

func (x *ImageUploadURLReply) GetImageId() uint64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *ImageUploadURLReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *ImageUploadURLReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_article_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateArticleRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateArticleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_article_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{3}
}

type GetMyArticleDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyArticleDetailRequest) Reset() {
	*x = GetMyArticleDetailRequest{}
	mi := &file_article_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyArticleDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyArticleDetailRequest) ProtoMessage() {}

func (x *GetMyArticleDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyArticleDetailRequest.ProtoReflect.Descriptor instead.
func (*GetMyArticleDetailRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyArticleDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_article_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArticleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateArticleRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateArticleRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ArticleIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleIDRequest) Reset() {
	*x = ArticleIDRequest{}
	mi := &file_article_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleIDRequest) ProtoMessage() {}

func (x *ArticleIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleIDRequest.ProtoReflect.Descriptor instead.
func (*ArticleIDRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{6}
}

func (x *ArticleIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_article_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ArticleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	LastId        uint64                 `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	IsDesc        bool                   `protobuf:"varint,5,opt,name=is_desc,json=isDesc,proto3" json:"is_desc"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListRequest) Reset() {
	*x = ArticleListRequest{}
	mi := &file_article_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListRequest) ProtoMessage() {}

func (x *ArticleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListRequest.ProtoReflect.Descriptor instead.
func (*ArticleListRequest) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{8}
}

func (x *ArticleListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleListRequest) GetLastId() uint64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ArticleListRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ArticleListRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArticleListRequest) GetIsDesc() bool {
	if x != nil {
		return x.IsDesc
	}
	return false
}

type ArticleListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ArticleListItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	LastId        uint64                 `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	Page          uint64                 `protobuf:"varint,4,opt,name=page,proto3" json:"page"`
	PageSize      uint64                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListReply) Reset() {
	*x = ArticleListReply{}
	mi := &file_article_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListReply) ProtoMessage() {}

func (x *ArticleListReply) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListReply.ProtoReflect.Descriptor instead.
func (*ArticleListReply) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{9}
}

func (x *ArticleListReply) GetList() []*ArticleListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ArticleListReply) GetLastId() uint64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ArticleListReply) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ArticleListReply) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ArticleListReply) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ArticleListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
	CreatedTime   int64                  `protobuf:"varint,5,opt,name=created_time,json=createdTime,proto3" json:"created_time"`
	UpdatedTime   int64                  `protobuf:"varint,6,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListItem) Reset() {
	*x = ArticleListItem{}
	mi := &file_article_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListItem) ProtoMessage() {}

func (x *ArticleListItem) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListItem.ProtoReflect.Descriptor instead.
func (*ArticleListItem) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{10}
}

func (x *ArticleListItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleListItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ArticleListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleListItem) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *ArticleListItem) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

type ArticleDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	AuthorNick    string                 `protobuf:"bytes,6,opt,name=author_nick,json=authorNick,proto3" json:"author_nick"`
	AuthorAvatar  string                 `protobuf:"bytes,7,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip"`
	CreatedTime   int64                  `protobuf:"varint,9,opt,name=created_time,json=createdTime,proto3" json:"created_time"`
	UpdatedTime   int64                  `protobuf:"varint,10,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time"`
	IsLiked       bool                   `protobuf:"varint,11,opt,name=is_liked,json=isLiked,proto3" json:"is_liked"`
	LikeCount     int64                  `protobuf:"varint,12,opt,name=like_count,json=likeCount,proto3" json:"like_count"`
	Images        []*ArticleImage        `protobuf:"bytes,13,rep,name=images,proto3" json:"images"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDetailReply) Reset() {
	*x = ArticleDetailReply{}
	mi := &file_article_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetailReply) ProtoMessage() {}

func (x *ArticleDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetailReply.ProtoReflect.Descriptor instead.
func (*ArticleDetailReply) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{11}
}

func (x *ArticleDetailReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleDetailReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleDetailReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleDetailReply) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ArticleDetailReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleDetailReply) GetAuthorNick() string {
	if x != nil {
		return x.AuthorNick
	}
	return ""
}

func (x *ArticleDetailReply) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *ArticleDetailReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ArticleDetailReply) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *ArticleDetailReply) GetUpdatedTime() int64 {
	if x != nil {
		return x.UpdatedTime
	}
	return 0
}

func (x *ArticleDetailReply) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *ArticleDetailReply) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticleDetailReply) GetImages() []*ArticleImage {
	if x != nil {
		return x.Images
	}
	return nil
}

type ArticleImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleImage) Reset() {
	*x = ArticleImage{}
	mi := &file_article_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleImage) ProtoMessage() {}

func (x *ArticleImage) ProtoReflect() protoreflect.Message {
	mi := &file_article_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleImage.ProtoReflect.Descriptor instead.
func (*ArticleImage) Descriptor() ([]byte, []int) {
	return file_article_article_proto_rawDescGZIP(), []int{12}
}

func (x *ArticleImage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_article_article_proto protoreflect.FileDescriptor

const file_article_article_proto_rawDesc = "" +
	"\n" +
	"\x15article/article.proto\x12\n" +
	"article.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"@\n" +
	"\x18GetImageUploadURLRequest\x12$\n" +
	"\bfile_ext\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18\n" +
	"R\afileExt\"a\n" +
	"\x13ImageUploadURLReply\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\x04R\aimageId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x94\x01\n" +
	"\x14CreateArticleRequest\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x05title\x12!\n" +
	"\acontent\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12#\n" +
	"\x06status\x18\x04 \x01(\x05B\v\xfaB\b\x1a\x060\x000\x020\x03R\x06status\"\f\n" +
	"\n" +
	"EmptyReply\"4\n" +
	"\x19GetMyArticleDetailRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x02id\"\xad\x01\n" +
	"\x14UpdateArticleRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x02id\x12 \n" +
	"\x05title\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x05title\x12!\n" +
	"\acontent\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12#\n" +
	"\x06status\x18\x05 \x01(\x05B\v\xfaB\b\x1a\x060\x000\x020\x03R\x06status\"+\n" +
	"\x10ArticleIDRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x02id\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xbf\x01\n" +
	"\x12ArticleListRequest\x129\n" +
	"\x06status\x18\x01 \x01(\x05B!\xfaB\x1e\x1a\x1c0\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x010\xff\xff\xff\xff\xff\xff\xff\xff\xff\x010\x010\x020\x03R\x06status\x12\x17\n" +
	"\alast_id\x18\x02 \x01(\x04R\x06lastId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12(\n" +
	"\tpage_size\x18\x04 \x01(\x04B\v\xfaB\b2\x06\x18\x14(\n" +
	"@\x01R\bpageSize\x12\x17\n" +
	"\ais_desc\x18\x05 \x01(\bR\x06isDesc\"\xa3\x01\n" +
	"\x10ArticleListReply\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.article.v1.ArticleListItemR\x04list\x12\x17\n" +
	"\alast_id\x18\x02 \x01(\x04R\x06lastId\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x04R\bpageSize\"\xa9\x01\n" +
	"\x0fArticleListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12!\n" +
	"\fcreated_time\x18\x05 \x01(\x03R\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\x06 \x01(\x03R\vupdatedTime\"\x88\x03\n" +
	"\x12ArticleDetailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1f\n" +
	"\vauthor_nick\x18\x06 \x01(\tR\n" +
	"authorNick\x12#\n" +
	"\rauthor_avatar\x18\a \x01(\tR\fauthorAvatar\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12!\n" +
	"\fcreated_time\x18\t \x01(\x03R\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\n" +
	" \x01(\x03R\vupdatedTime\x12\x19\n" +
	"\bis_liked\x18\v \x01(\bR\aisLiked\x12\x1d\n" +
	"\n" +
	"like_count\x18\f \x01(\x03R\tlikeCount\x120\n" +
	"\x06images\x18\r \x03(\v2\x18.article.v1.ArticleImageR\x06images\"0\n" +
	"\fArticleImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url2\x84\n" +
	"\n" +
	"\x0eArticleService\x12\x86\x01\n" +
	"\x11GetImageUploadURL\x12$.article.v1.GetImageUploadURLRequest\x1a\x1f.article.v1.ImageUploadURLReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/admin/article/image/upload-url\x12k\n" +
	"\rCreateArticle\x12 .article.v1.CreateArticleRequest\x1a\x16.article.v1.EmptyReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/admin/article/create\x12}\n" +
	"\x12GetMyArticleDetail\x12%.article.v1.GetMyArticleDetailRequest\x1a\x1e.article.v1.ArticleDetailReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/admin/article/me/detail\x12k\n" +
	"\rUpdateArticle\x12 .article.v1.UpdateArticleRequest\x1a\x16.article.v1.EmptyReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/admin/article/update\x12i\n" +
	"\x0ePublishArticle\x12\x1c.article.v1.ArticleIDRequest\x1a\x16.article.v1.EmptyReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/admin/article/publish\x12r\n" +
	"\x10GetArticleDetail\x12\x1c.article.v1.ArticleIDRequest\x1a\x1e.article.v1.ArticleDetailReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/optional/article/detail\x12k\n" +
	"\x0eListMyArticles\x12\x1e.article.v1.ArticleListRequest\x1a\x1c.article.v1.ArticleListReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/admin/article/list\x12p\n" +
	"\x12MoveArticleToTrash\x12 .article.v1.DeleteArticleRequest\x1a\x16.article.v1.EmptyReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/admin/article/delete\x12t\n" +
	"\x11ListTrashArticles\x12\x1e.article.v1.ArticleListRequest\x1a\x1c.article.v1.ArticleListReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/admin/article/trash/list\x12o\n" +
	"\x0eRecoverArticle\x12\x1c.article.v1.ArticleIDRequest\x1a\x16.article.v1.EmptyReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/admin/article/trash/recover\x12k\n" +
	"\fClearArticle\x12\x1c.article.v1.ArticleIDRequest\x1a\x16.article.v1.EmptyReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/admin/article/trash/clearBBZ@codeup.aliyun.com/qimao/blog/ai-blog/backend/api/article;articleb\x06proto3"

var (
	file_article_article_proto_rawDescOnce sync.Once
	file_article_article_proto_rawDescData []byte
)

func file_article_article_proto_rawDescGZIP() []byte {
	file_article_article_proto_rawDescOnce.Do(func() {
		file_article_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_article_proto_rawDesc), len(file_article_article_proto_rawDesc)))
	})
	return file_article_article_proto_rawDescData
}

var file_article_article_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_article_article_proto_goTypes = []any{
	(*GetImageUploadURLRequest)(nil),  // 0: article.v1.GetImageUploadURLRequest
	(*ImageUploadURLReply)(nil),       // 1: article.v1.ImageUploadURLReply
	(*CreateArticleRequest)(nil),      // 2: article.v1.CreateArticleRequest
	(*EmptyReply)(nil),                // 3: article.v1.EmptyReply
	(*GetMyArticleDetailRequest)(nil), // 4: article.v1.GetMyArticleDetailRequest
	(*UpdateArticleRequest)(nil),      // 5: article.v1.UpdateArticleRequest
	(*ArticleIDRequest)(nil),          // 6: article.v1.ArticleIDRequest
	(*DeleteArticleRequest)(nil),      // 7: article.v1.DeleteArticleRequest
	(*ArticleListRequest)(nil),        // 8: article.v1.ArticleListRequest
	(*ArticleListReply)(nil),          // 9: article.v1.ArticleListReply
	(*ArticleListItem)(nil),           // 10: article.v1.ArticleListItem
	(*ArticleDetailReply)(nil),        // 11: article.v1.ArticleDetailReply
	(*ArticleImage)(nil),              // 12: article.v1.ArticleImage
}
var file_article_article_proto_depIdxs = []int32{
	10, // 0: article.v1.ArticleListReply.list:type_name -> article.v1.ArticleListItem
	12, // 1: article.v1.ArticleDetailReply.images:type_name -> article.v1.ArticleImage
	0,  // 2: article.v1.ArticleService.GetImageUploadURL:input_type -> article.v1.GetImageUploadURLRequest
	2,  // 3: article.v1.ArticleService.CreateArticle:input_type -> article.v1.CreateArticleRequest
	4,  // 4: article.v1.ArticleService.GetMyArticleDetail:input_type -> article.v1.GetMyArticleDetailRequest
	5,  // 5: article.v1.ArticleService.UpdateArticle:input_type -> article.v1.UpdateArticleRequest
	6,  // 6: article.v1.ArticleService.PublishArticle:input_type -> article.v1.ArticleIDRequest
	6,  // 7: article.v1.ArticleService.GetArticleDetail:input_type -> article.v1.ArticleIDRequest
	8,  // 8: article.v1.ArticleService.ListMyArticles:input_type -> article.v1.ArticleListRequest
	7,  // 9: article.v1.ArticleService.MoveArticleToTrash:input_type -> article.v1.DeleteArticleRequest
	8,  // 10: article.v1.ArticleService.ListTrashArticles:input_type -> article.v1.ArticleListRequest
	6,  // 11: article.v1.ArticleService.RecoverArticle:input_type -> article.v1.ArticleIDRequest
	6,  // 12: article.v1.ArticleService.ClearArticle:input_type -> article.v1.ArticleIDRequest
	1,  // 13: article.v1.ArticleService.GetImageUploadURL:output_type -> article.v1.ImageUploadURLReply
	3,  // 14: article.v1.ArticleService.CreateArticle:output_type -> article.v1.EmptyReply
	11, // 15: article.v1.ArticleService.GetMyArticleDetail:output_type -> article.v1.ArticleDetailReply
	3,  // 16: article.v1.ArticleService.UpdateArticle:output_type -> article.v1.EmptyReply
	3,  // 17: article.v1.ArticleService.PublishArticle:output_type -> article.v1.EmptyReply
	11, // 18: article.v1.ArticleService.GetArticleDetail:output_type -> article.v1.ArticleDetailReply
	9,  // 19: article.v1.ArticleService.ListMyArticles:output_type -> article.v1.ArticleListReply
	3,  // 20: article.v1.ArticleService.MoveArticleToTrash:output_type -> article.v1.EmptyReply
	9,  // 21: article.v1.ArticleService.ListTrashArticles:output_type -> article.v1.ArticleListReply
	3,  // 22: article.v1.ArticleService.RecoverArticle:output_type -> article.v1.EmptyReply
	3,  // 23: article.v1.ArticleService.ClearArticle:output_type -> article.v1.EmptyReply
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_article_article_proto_init() }
func file_article_article_proto_init() {
	if File_article_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_article_proto_rawDesc), len(file_article_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_article_proto_goTypes,
		DependencyIndexes: file_article_article_proto_depIdxs,
		MessageInfos:      file_article_article_proto_msgTypes,
	}.Build()
	File_article_article_proto = out.File
	file_article_article_proto_goTypes = nil
	file_article_article_proto_depIdxs = nil
}
