// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: blogopen/v1/comment.proto

package blogopenv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCommentStatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCommentStatsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommentStatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCommentStatsRequestMultiError, or nil if none found.
func (m *GetCommentStatsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommentStatsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetCommentId() <= 0 {
		err := GetCommentStatsRequestValidationError{
			field:  "CommentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCommentStatsRequestMultiError(errors)
	}

	return nil
}

// GetCommentStatsRequestMultiError is an error wrapping multiple validation
// errors returned by GetCommentStatsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCommentStatsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommentStatsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommentStatsRequestMultiError) AllErrors() []error { return m }

// GetCommentStatsRequestValidationError is the validation error returned by
// GetCommentStatsRequest.Validate if the designated constraints aren't met.
type GetCommentStatsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommentStatsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommentStatsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommentStatsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommentStatsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommentStatsRequestValidationError) ErrorName() string {
	return "GetCommentStatsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommentStatsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommentStatsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommentStatsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommentStatsRequestValidationError{}

// Validate checks the field values on GetCommentStatsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCommentStatsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommentStatsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCommentStatsReplyMultiError, or nil if none found.
func (m *GetCommentStatsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommentStatsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CommentId

	// no validation rules for HotValue

	// no validation rules for LikeCount

	if len(errors) > 0 {
		return GetCommentStatsReplyMultiError(errors)
	}

	return nil
}

// GetCommentStatsReplyMultiError is an error wrapping multiple validation
// errors returned by GetCommentStatsReply.ValidateAll() if the designated
// constraints aren't met.
type GetCommentStatsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommentStatsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommentStatsReplyMultiError) AllErrors() []error { return m }

// GetCommentStatsReplyValidationError is the validation error returned by
// GetCommentStatsReply.Validate if the designated constraints aren't met.
type GetCommentStatsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommentStatsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommentStatsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommentStatsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommentStatsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommentStatsReplyValidationError) ErrorName() string {
	return "GetCommentStatsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommentStatsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommentStatsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommentStatsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommentStatsReplyValidationError{}
