// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.35.1
// source: blogopen/v1/comment.proto

package blogopenv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCommentStatsRequest 是评论统计查询请求。
type GetCommentStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId uint64 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id"`
}

func (x *GetCommentStatsRequest) Reset() {
	*x = GetCommentStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogopen_v1_comment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentStatsRequest) ProtoMessage() {}

func (x *GetCommentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blogopen_v1_comment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentStatsRequest) Descriptor() ([]byte, []int) {
	return file_blogopen_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommentStatsRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

// GetCommentStatsReply 是评论点赞与热度统计。
type GetCommentStatsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId uint64 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id"`
	HotValue  int64  `protobuf:"varint,2,opt,name=hot_value,json=hotValue,proto3" json:"hot_value"`
	LikeCount int64  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count"`
}

func (x *GetCommentStatsReply) Reset() {
	*x = GetCommentStatsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blogopen_v1_comment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentStatsReply) ProtoMessage() {}

func (x *GetCommentStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_blogopen_v1_comment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentStatsReply.ProtoReflect.Descriptor instead.
func (*GetCommentStatsReply) Descriptor() ([]byte, []int) {
	return file_blogopen_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommentStatsReply) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *GetCommentStatsReply) GetHotValue() int64 {
	if x != nil {
		return x.HotValue
	}
	return 0
}

func (x *GetCommentStatsReply) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

var File_blogopen_v1_comment_proto protoreflect.FileDescriptor

var file_blogopen_v1_comment_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x6c, 0x6f, 0x67, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x6c, 0x6f,
	0x67, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x40, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x68,
	0x6f, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6b,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x6b, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x6f, 0x70, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x49, 0x5a, 0x47, 0x63, 0x6f, 0x64, 0x65, 0x75, 0x70, 0x2e, 0x61, 0x6c,
	0x69, 0x79, 0x75, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x69, 0x6d, 0x61, 0x6f, 0x2f, 0x62,
	0x6c, 0x6f, 0x67, 0x2f, 0x61, 0x69, 0x2d, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x76, 0x31, 0x3b, 0x62, 0x6c, 0x6f, 0x67, 0x6f, 0x70, 0x65, 0x6e, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blogopen_v1_comment_proto_rawDescOnce sync.Once
	file_blogopen_v1_comment_proto_rawDescData = file_blogopen_v1_comment_proto_rawDesc
)

func file_blogopen_v1_comment_proto_rawDescGZIP() []byte {
	file_blogopen_v1_comment_proto_rawDescOnce.Do(func() {
		file_blogopen_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(file_blogopen_v1_comment_proto_rawDescData)
	})
	return file_blogopen_v1_comment_proto_rawDescData
}

var file_blogopen_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blogopen_v1_comment_proto_goTypes = []interface{}{
	(*GetCommentStatsRequest)(nil), // 0: blogopen.v1.GetCommentStatsRequest
	(*GetCommentStatsReply)(nil),   // 1: blogopen.v1.GetCommentStatsReply
}
var file_blogopen_v1_comment_proto_depIdxs = []int32{
	0, // 0: blogopen.v1.CommentService.GetCommentStats:input_type -> blogopen.v1.GetCommentStatsRequest
	1, // 1: blogopen.v1.CommentService.GetCommentStats:output_type -> blogopen.v1.GetCommentStatsReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blogopen_v1_comment_proto_init() }
func file_blogopen_v1_comment_proto_init() {
	if File_blogopen_v1_comment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blogopen_v1_comment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blogopen_v1_comment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentStatsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blogopen_v1_comment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blogopen_v1_comment_proto_goTypes,
		DependencyIndexes: file_blogopen_v1_comment_proto_depIdxs,
		MessageInfos:      file_blogopen_v1_comment_proto_msgTypes,
	}.Build()
	File_blogopen_v1_comment_proto = out.File
	file_blogopen_v1_comment_proto_rawDesc = nil
	file_blogopen_v1_comment_proto_goTypes = nil
	file_blogopen_v1_comment_proto_depIdxs = nil
}
