// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: blogopen/v1/user.proto

package blogopenv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_GetUserBasicInfo_FullMethodName  = "/blogopen.v1.UserService/GetUserBasicInfo"
	UserService_GetPublicUserInfo_FullMethodName = "/blogopen.v1.UserService/GetPublicUserInfo"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// GetUserBasicInfo 供内部服务查询用户基本信息和脱敏登录地区。
	GetUserBasicInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserBasicInfoReply, error)
	// GetPublicUserInfo 供外部合作方查询用户公开资料。
	GetPublicUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*PublicUserInfoReply, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserBasicInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserBasicInfoReply, error) {
	out := new(UserBasicInfoReply)
	err := c.cc.Invoke(ctx, UserService_GetUserBasicInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPublicUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*PublicUserInfoReply, error) {
	out := new(PublicUserInfoReply)
	err := c.cc.Invoke(ctx, UserService_GetPublicUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// GetUserBasicInfo 供内部服务查询用户基本信息和脱敏登录地区。
	GetUserBasicInfo(context.Context, *GetUserInfoRequest) (*UserBasicInfoReply, error)
	// GetPublicUserInfo 供外部合作方查询用户公开资料。
	GetPublicUserInfo(context.Context, *GetUserInfoRequest) (*PublicUserInfoReply, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUserBasicInfo(context.Context, *GetUserInfoRequest) (*UserBasicInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBasicInfo not implemented")
}
func (UnimplementedUserServiceServer) GetPublicUserInfo(context.Context, *GetUserInfoRequest) (*PublicUserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicUserInfo not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserBasicInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPublicUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPublicUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPublicUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPublicUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blogopen.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserBasicInfo",
			Handler:    _UserService_GetUserBasicInfo_Handler,
		},
		{
			MethodName: "GetPublicUserInfo",
			Handler:    _UserService_GetPublicUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blogopen/v1/user.proto",
}
