// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: blogopen/v1/user.proto

package blogopenv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetUserInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserInfoRequestMultiError, or nil if none found.
func (m *GetUserInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := GetUserInfoRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserInfoRequestMultiError(errors)
	}

	return nil
}

// GetUserInfoRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserInfoRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserInfoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserInfoRequestMultiError) AllErrors() []error { return m }

// GetUserInfoRequestValidationError is the validation error returned by
// GetUserInfoRequest.Validate if the designated constraints aren't met.
type GetUserInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserInfoRequestValidationError) ErrorName() string {
	return "GetUserInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserInfoRequestValidationError{}

// Validate checks the field values on UserBasicInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserBasicInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserBasicInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserBasicInfoReplyMultiError, or nil if none found.
func (m *UserBasicInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UserBasicInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Nickname

	// no validation rules for Avatar

	// no validation rules for LastLoginTime

	// no validation rules for LastLoginIp

	if len(errors) > 0 {
		return UserBasicInfoReplyMultiError(errors)
	}

	return nil
}

// UserBasicInfoReplyMultiError is an error wrapping multiple validation errors
// returned by UserBasicInfoReply.ValidateAll() if the designated constraints
// aren't met.
type UserBasicInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserBasicInfoReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserBasicInfoReplyMultiError) AllErrors() []error { return m }

// UserBasicInfoReplyValidationError is the validation error returned by
// UserBasicInfoReply.Validate if the designated constraints aren't met.
type UserBasicInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserBasicInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserBasicInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserBasicInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserBasicInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserBasicInfoReplyValidationError) ErrorName() string {
	return "UserBasicInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UserBasicInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserBasicInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserBasicInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserBasicInfoReplyValidationError{}

// Validate checks the field values on PublicUserInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PublicUserInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PublicUserInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PublicUserInfoReplyMultiError, or nil if none found.
func (m *PublicUserInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PublicUserInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Avatar

	// no validation rules for Nickname

	if len(errors) > 0 {
		return PublicUserInfoReplyMultiError(errors)
	}

	return nil
}

// PublicUserInfoReplyMultiError is an error wrapping multiple validation
// errors returned by PublicUserInfoReply.ValidateAll() if the designated
// constraints aren't met.
type PublicUserInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PublicUserInfoReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PublicUserInfoReplyMultiError) AllErrors() []error { return m }

// PublicUserInfoReplyValidationError is the validation error returned by
// PublicUserInfoReply.Validate if the designated constraints aren't met.
type PublicUserInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PublicUserInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PublicUserInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PublicUserInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PublicUserInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PublicUserInfoReplyValidationError) ErrorName() string {
	return "PublicUserInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PublicUserInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPublicUserInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PublicUserInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PublicUserInfoReplyValidationError{}
