// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.7
// source: book/book.proto

package book

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Book_ShowBook_FullMethodName   = "/BookServer.Book/ShowBook"
	Book_BookList_FullMethodName   = "/BookServer.Book/BookList"
	Book_UpdateBook_FullMethodName = "/BookServer.Book/UpdateBook"
	Book_DelBook_FullMethodName    = "/BookServer.Book/DelBook"
)

// BookClient is the client API for Book service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookClient interface {
	// GET /api/ShowBook 123
	ShowBook(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error)
	// GET /api/BookList
	BookList(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error)
	// POST /api/UpdateBook
	UpdateBook(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error)
	// POST /api/DelBook
	DelBook(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error)
}

type bookClient struct {
	cc grpc.ClientConnInterface
}

func NewBookClient(cc grpc.ClientConnInterface) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) ShowBook(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error) {
	out := new(ReplyBook)
	err := c.cc.Invoke(ctx, Book_ShowBook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) BookList(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error) {
	out := new(ReplyBook)
	err := c.cc.Invoke(ctx, Book_BookList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) UpdateBook(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error) {
	out := new(ReplyBook)
	err := c.cc.Invoke(ctx, Book_UpdateBook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) DelBook(ctx context.Context, in *RequestBook, opts ...grpc.CallOption) (*ReplyBook, error) {
	out := new(ReplyBook)
	err := c.cc.Invoke(ctx, Book_DelBook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServer is the server API for Book service.
// All implementations must embed UnimplementedBookServer
// for forward compatibility
type BookServer interface {
	// GET /api/ShowBook 123
	ShowBook(context.Context, *RequestBook) (*ReplyBook, error)
	// GET /api/BookList
	BookList(context.Context, *RequestBook) (*ReplyBook, error)
	// POST /api/UpdateBook
	UpdateBook(context.Context, *RequestBook) (*ReplyBook, error)
	// POST /api/DelBook
	DelBook(context.Context, *RequestBook) (*ReplyBook, error)
	mustEmbedUnimplementedBookServer()
}

// UnimplementedBookServer must be embedded to have forward compatible implementations.
type UnimplementedBookServer struct {
}

func (UnimplementedBookServer) ShowBook(context.Context, *RequestBook) (*ReplyBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowBook not implemented")
}
func (UnimplementedBookServer) BookList(context.Context, *RequestBook) (*ReplyBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookList not implemented")
}
func (UnimplementedBookServer) UpdateBook(context.Context, *RequestBook) (*ReplyBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBookServer) DelBook(context.Context, *RequestBook) (*ReplyBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelBook not implemented")
}
func (UnimplementedBookServer) mustEmbedUnimplementedBookServer() {}

// UnsafeBookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServer will
// result in compilation errors.
type UnsafeBookServer interface {
	mustEmbedUnimplementedBookServer()
}

func RegisterBookServer(s grpc.ServiceRegistrar, srv BookServer) {
	s.RegisterService(&Book_ServiceDesc, srv)
}

func _Book_ShowBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).ShowBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Book_ShowBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).ShowBook(ctx, req.(*RequestBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_BookList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).BookList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Book_BookList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).BookList(ctx, req.(*RequestBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Book_UpdateBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).UpdateBook(ctx, req.(*RequestBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_DelBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).DelBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Book_DelBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).DelBook(ctx, req.(*RequestBook))
	}
	return interceptor(ctx, in, info, handler)
}

// Book_ServiceDesc is the grpc.ServiceDesc for Book service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Book_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BookServer.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowBook",
			Handler:    _Book_ShowBook_Handler,
		},
		{
			MethodName: "BookList",
			Handler:    _Book_BookList_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Book_UpdateBook_Handler,
		},
		{
			MethodName: "DelBook",
			Handler:    _Book_DelBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book/book.proto",
}
