// Code generated by protoc-gen-gin-http. DO NOT EDIT.
// versions:
// - protoc-gen-gin-http v0.0.5
// - protoc             v3.21.7
// source: book/book.proto

package book

import (
	bytes "bytes"
	log "codeup.aliyun.com/qimao/leo/leo/log"
	code_encoding "codeup.aliyun.com/qimao/leo/lib/code-encoding"
	form "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	errassets "codeup.aliyun.com/qimao/leo/lib/errassets"
	json "codeup.aliyun.com/qimao/leo/lib/pkg/json"
	render "codeup.aliyun.com/qimao/leo/lib/render"
	gin "github.com/gin-gonic/gin"
	io "io"
	http "net/http"
)

import (
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/json"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/proto"
)

// 引入指定包
var _ = new(gin.Context)
var _ = new(bytes.Buffer)
var _ = code_encoding.Version
var _ = http.StatusOK
var _ = errassets.LevelToast
var _ = log.LevelDebug
var _ = io.EOF
var _ = json.Marshal
var _ = form.Name

// 单纯引入 render 包，后续render 包加个常量
// var _, _  = render.render.JSON(0,0)
// 定义兼容客户端的通用返回结构体
type Response struct {
	Data any `json:"data"`
}

const OperationBookBookList = "/BookServer.Book/BookList"
const OperationBookDelBook = "/BookServer.Book/DelBook"
const OperationBookShowBook = "/BookServer.Book/ShowBook"
const OperationBookUpdateBook = "/BookServer.Book/UpdateBook"

type BookHTTPServerController interface {
	BookList(*gin.Context, *RequestBook) (*ReplyBook, error)
	DelBook(*gin.Context, *RequestBook) (*ReplyBook, error)
	ShowBook(*gin.Context, *RequestBook) (*ReplyBook, error)
	UpdateBook(*gin.Context, *RequestBook) (*ReplyBook, error)
}

func RegisterBookHTTPServerController(router *gin.RouterGroup, srv BookHTTPServerController) {
	router.GET("/api/ShowBook", _Book_ShowBook0_HTTP_Handler(srv))
	router.GET("/api/BookList", _Book_BookList0_HTTP_Handler(srv))
	router.POST("/api/UpdateBook", _Book_UpdateBook0_HTTP_Handler(srv))
	router.POST("/api/DelBook", _Book_DelBook0_HTTP_Handler(srv))
}

func _Book_ShowBook0_HTTP_Handler(srv BookHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RequestBook
		// get
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		// get end
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.ShowBook(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/BookServer.Book/ShowBook err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := Response{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/BookServer.Book/ShowBook err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _Book_BookList0_HTTP_Handler(srv BookHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RequestBook
		// get
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		// get end
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.BookList(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/BookServer.Book/BookList err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := Response{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/BookServer.Book/BookList err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _Book_UpdateBook0_HTTP_Handler(srv BookHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RequestBook
		// post
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		// post end
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.UpdateBook(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/BookServer.Book/UpdateBook err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := Response{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/BookServer.Book/UpdateBook err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _Book_DelBook0_HTTP_Handler(srv BookHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RequestBook
		// post
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		// post end
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.DelBook(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/BookServer.Book/DelBook err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := Response{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/BookServer.Book/DelBook err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}
