// Code generated by protoc-gen-gin-http. DO NOT EDIT.
// versions:
// - protoc-gen-gin-http v0.0.6
// - protoc             v7.35.1
// source: like/like.proto

package like

import (
	bytes "bytes"
	log "codeup.aliyun.com/qimao/leo/leo/log"
	code_encoding "codeup.aliyun.com/qimao/leo/lib/code-encoding"
	form "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	errassets "codeup.aliyun.com/qimao/leo/lib/errassets"
	json "codeup.aliyun.com/qimao/leo/lib/pkg/json"
	render "codeup.aliyun.com/qimao/leo/lib/render"
	gin "github.com/gin-gonic/gin"
	io "io"
	http "net/http"
)

import (
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/json"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/proto"
)

// 引入指定包
var _ = new(gin.Context)
var _ = new(bytes.Buffer)
var _ = code_encoding.Version
var _ = http.StatusOK
var _ = errassets.LevelToast
var _ = log.LevelDebug
var _ = io.EOF
var _ = json.Marshal
var _ = form.Name

// 单纯引入 render 包，后续render 包加个常量
// var _, _  = render.render.JSON(0,0)

type LikeServiceResponse struct {
	Data any `json:"data"`
}

const OperationLikeServiceCancelArticleLike = "/like.v1.LikeService/CancelArticleLike"
const OperationLikeServiceLikeArticle = "/like.v1.LikeService/LikeArticle"

type LikeServiceHTTPServerController interface {
	CancelArticleLike(*gin.Context, *ArticleLikeRequest) (*EmptyReply, error)
	LikeArticle(*gin.Context, *ArticleLikeRequest) (*EmptyReply, error)
}

func RegisterLikeServiceHTTPServerController(router *gin.RouterGroup, srv LikeServiceHTTPServerController) {
	router.POST("/auth/article/like", _LikeService_LikeArticle0_HTTP_Handler(srv))
	router.POST("/auth/article/cancel_like", _LikeService_CancelArticleLike0_HTTP_Handler(srv))
}

func _LikeService_LikeArticle0_HTTP_Handler(srv LikeServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ArticleLikeRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.LikeArticle(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/like.v1.LikeService/LikeArticle err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := LikeServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/like.v1.LikeService/LikeArticle err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _LikeService_CancelArticleLike0_HTTP_Handler(srv LikeServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ArticleLikeRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.CancelArticleLike(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/like.v1.LikeService/CancelArticleLike err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := LikeServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/like.v1.LikeService/CancelArticleLike err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}
