// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/app/service"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/clients"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/clients/ipregion"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/clients/objectstorage"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/conf"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/article"
	repo3 "codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/article/repo"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/book"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/book/repo"
	repo4 "codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/like/repo"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/user"
	repo2 "codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/user/repo"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/server"
	"codeup.aliyun.com/qimao/leo/leo/transport/lgrpc"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp() (*httpApplication, func(), error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	mysqlClient, cleanup, err := clients.NewMysqlClient()
	if err != nil {
		return nil, nil, err
	}
	mysqlLogClient, cleanup2, err := clients.NewLogMysqlClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := clients.NewRedisClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	hdRepo := repo.NewHdRepo(mysqlClient, mysqlLogClient, redisClient)
	helloworldService := book.NewHelloworld(hdRepo)
	greeterHTTPServerController := service.NewBlogServer(helloworldService)
	bookHTTPServerController := service.NewBookServer()
	userRepository := repo2.NewUserRepository(mysqlClient)
	passwordHasher := user.NewPBKDF2PasswordHasher()
	sessionRepository := repo2.NewSessionRepository(redisClient)
	userService := user.NewServiceWithSession(userRepository, userRepository, passwordHasher, sessionRepository)
	resolver, cleanup4, err := ipregion.NewConfiguredResolver(config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v, err := service.ProvideTrustedProxyCIDRs(config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userServiceHTTPServerController := service.NewUserServer(userService, resolver, v)
	transactionClient := repo3.ProvideTransactionClient(mysqlClient)
	repository := repo3.NewRepository(mysqlClient, transactionClient)
	storage, err := objectstorage.NewStorage(config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	queryRepository := repo4.NewQueryRepository(mysqlClient)
	submissionGuard := repo3.NewSubmissionGuard(redisClient)
	allowedImageExtensions := objectstorage.ProvideAllowedImageExtensions(config)
	articleService, err := article.NewService(repository, storage, queryRepository, submissionGuard, allowedImageExtensions)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	articleServiceHTTPServerController := service.NewArticleServer(articleService, storage, resolver)
	registerServer := server.NewHTTPServer(greeterHTTPServerController, bookHTTPServerController, userServiceHTTPServerController, articleServiceHTTPServerController, sessionRepository)
	articleDeletionReconciler := service.NewArticleDeletionReconciler(articleService)
	serverHttpApplication := newApp(config, registerServer, articleDeletionReconciler)
	return serverHttpApplication, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wireGrpcApp init application.
func wireGrpcApp() (*lgrpc.Server, func(), error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	mysqlClient, cleanup, err := clients.NewMysqlClient()
	if err != nil {
		return nil, nil, err
	}
	mysqlLogClient, cleanup2, err := clients.NewLogMysqlClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := clients.NewRedisClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	hdRepo := repo.NewHdRepo(mysqlClient, mysqlLogClient, redisClient)
	helloworldService := book.NewHelloworld(hdRepo)
	greeterServer := service.NewGrpcBlogServer(helloworldService)
	bookServer := service.NewGrpcBookServer()
	grpcServer := server.NewGrpcServer(greeterServer, bookServer)
	lgrpcServer := newGrpcApp(config, grpcServer)
	return lgrpcServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
