// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/app/service"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/clients"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/conf"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/book"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/book/repo"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/user"
	repo2 "codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/user/repo"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/server"
	"codeup.aliyun.com/qimao/leo/leo/transport/ginhttp"
	"codeup.aliyun.com/qimao/leo/leo/transport/lgrpc"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp() (*ginhttp.Server, func(), error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	mysqlClient, cleanup, err := clients.NewMysqlClient()
	if err != nil {
		return nil, nil, err
	}
	mysqlLogClient, cleanup2, err := clients.NewLogMysqlClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := clients.NewRedisClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	hdRepo := repo.NewHdRepo(mysqlClient, mysqlLogClient, redisClient)
	helloworldService := book.NewHelloworld(hdRepo)
	greeterHTTPServerController := service.NewBlogServer(helloworldService)
	bookHTTPServerController := service.NewBookServer()
	repository := repo2.NewUserRepository(mysqlClient)
	passwordHasher := user.NewPBKDF2PasswordHasher()
	userService := user.NewService(repository, passwordHasher)
	userServiceHTTPServerController := service.NewUserServer(userService)
	sessionRepository := repo2.NewSessionRepository(redisClient)
	registerServer := server.NewHTTPServer(greeterHTTPServerController, bookHTTPServerController, userServiceHTTPServerController, sessionRepository)
	ginhttpServer := newApp(config, registerServer)
	return ginhttpServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wireGrpcApp init application.
func wireGrpcApp() (*lgrpc.Server, func(), error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	mysqlClient, cleanup, err := clients.NewMysqlClient()
	if err != nil {
		return nil, nil, err
	}
	mysqlLogClient, cleanup2, err := clients.NewLogMysqlClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := clients.NewRedisClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	hdRepo := repo.NewHdRepo(mysqlClient, mysqlLogClient, redisClient)
	helloworldService := book.NewHelloworld(hdRepo)
	greeterServer := service.NewGrpcBlogServer(helloworldService)
	bookServer := service.NewGrpcBookServer()
	grpcServer := server.NewGrpcServer(greeterServer, bookServer)
	lgrpcServer := newGrpcApp(config, grpcServer)
	return lgrpcServer, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
