// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package job

import (
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/app/job"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/clients"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/conf"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/book"
	"codeup.aliyun.com/qimao/blog/ai-blog/backend/internal/domain/book/repo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewBlogJob() (*job.BlogJob, func(), error) {
	mysqlClient, cleanup, err := clients.NewMysqlClient()
	if err != nil {
		return nil, nil, err
	}
	mysqlLogClient, cleanup2, err := clients.NewLogMysqlClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := clients.NewRedisClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	hdRepo := repo.NewHdRepo(mysqlClient, mysqlLogClient, redisClient)
	helloworldService := book.NewHelloworld(hdRepo)
	blogJob := job.NewJob(helloworldService)
	return blogJob, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(conf.ProviderSet, job.ProviderJobSet, clients.ProviderClientsSet, domain.DomainProviderAppSet)
