// Code generated by protoc-gen-gin-http. DO NOT EDIT.
// versions:
// - protoc-gen-gin-http v0.0.5
// - protoc             v3.21.7
// source: helloworld/helloworld.proto

package helloworld

import (
	bytes "bytes"
	log "codeup.aliyun.com/qimao/leo/leo/log"
	code_encoding "codeup.aliyun.com/qimao/leo/lib/code-encoding"
	form "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	errassets "codeup.aliyun.com/qimao/leo/lib/errassets"
	json "codeup.aliyun.com/qimao/leo/lib/pkg/json"
	render "codeup.aliyun.com/qimao/leo/lib/render"
	gin "github.com/gin-gonic/gin"
	io "io"
	http "net/http"
)

import (
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/json"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/proto"
)

// 引入指定包
var _ = new(gin.Context)
var _ = new(bytes.Buffer)
var _ = code_encoding.Version
var _ = http.StatusOK
var _ = errassets.LevelToast
var _ = log.LevelDebug
var _ = io.EOF
var _ = json.Marshal
var _ = form.Name

// 单纯引入 render 包，后续render 包加个常量
// var _, _  = render.render.JSON(0,0)
// 定义兼容客户端的通用返回结构体
type Response struct {
	Data any `json:"data"`
}

const OperationGreeterDoSome = "/helloworld.Greeter/DoSome"
const OperationGreeterSayHello = "/helloworld.Greeter/SayHello"

type GreeterHTTPServerController interface {
	DoSome(*gin.Context, *HelloRequest) (*HelloReply, error)
	SayHello(*gin.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterHTTPServerController(router *gin.RouterGroup, srv GreeterHTTPServerController) {
	router.POST("/helloworld.Greeter/SayHello", _Greeter_SayHello0_HTTP_Handler(srv))
	router.GET("/v1/DoSome", _Greeter_DoSome0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in HelloRequest
		// get
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		// get end
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.SayHello(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/helloworld.Greeter/SayHello err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := Response{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/helloworld.Greeter/SayHello err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _Greeter_DoSome0_HTTP_Handler(srv GreeterHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in HelloRequest
		// get
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		// get end
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.DoSome(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/helloworld.Greeter/DoSome err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := Response{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/helloworld.Greeter/DoSome err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}
