// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: user/user.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest 是用户注册请求。
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// GetMyProfileRequest 是当前用户资料查询请求。
type GetMyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyProfileRequest) Reset() {
	*x = GetMyProfileRequest{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyProfileRequest) ProtoMessage() {}

func (x *GetMyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyProfileRequest.ProtoReflect.Descriptor instead.
func (*GetMyProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

// GetPublicProfileRequest 是公开资料查询请求。
type GetPublicProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicProfileRequest) Reset() {
	*x = GetPublicProfileRequest{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicProfileRequest) ProtoMessage() {}

func (x *GetPublicProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPublicProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublicProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UpdateMyProfileRequest 是当前用户资料修改请求。
type UpdateMyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyProfileRequest) Reset() {
	*x = UpdateMyProfileRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyProfileRequest) ProtoMessage() {}

func (x *UpdateMyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMyProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMyProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateMyProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// EmptyReply 表示业务成功但不返回数据。
type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

// ProfileReply 是当前用户可见的完整资料。
type ProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	LastLoginTime int64                  `protobuf:"varint,5,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	LastLoginIp   string                 `protobuf:"bytes,6,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReply) Reset() {
	*x = ProfileReply{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReply) ProtoMessage() {}

func (x *ProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReply.ProtoReflect.Descriptor instead.
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ProfileReply) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ProfileReply) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *ProfileReply) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

// PublicProfileReply 是游客可见的公开资料。
type PublicProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicProfileReply) Reset() {
	*x = PublicProfileReply{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicProfileReply) ProtoMessage() {}

func (x *PublicProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicProfileReply.ProtoReflect.Descriptor instead.
func (*PublicProfileReply) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *PublicProfileReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicProfileReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PublicProfileReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"~\n" +
	"\x0fRegisterRequest\x12%\n" +
	"\bnickname\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\bnickname\x12\x1f\n" +
	"\x05phone\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x05phone\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\"\x15\n" +
	"\x13GetMyProfileRequest\";\n" +
	"\x17GetPublicProfileRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\"a\n" +
	"\x16UpdateMyProfileRequest\x12%\n" +
	"\bnickname\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\bnickname\x12 \n" +
	"\x06avatar\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\x06avatar\"\f\n" +
	"\n" +
	"EmptyReply\"\xb2\x01\n" +
	"\fProfileReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\x12&\n" +
	"\x0flast_login_time\x18\x05 \x01(\x03R\rlastLoginTime\x12\"\n" +
	"\rlast_login_ip\x18\x06 \x01(\tR\vlastLoginIp\"X\n" +
	"\x12PublicProfileReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar2\x99\x03\n" +
	"\vUserService\x12T\n" +
	"\bRegister\x12\x18.user.v1.RegisterRequest\x1a\x13.user.v1.EmptyReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/register\x12]\n" +
	"\fGetMyProfile\x12\x1c.user.v1.GetMyProfileRequest\x1a\x15.user.v1.ProfileReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/auth/my/profile\x12h\n" +
	"\x10GetPublicProfile\x12 .user.v1.GetPublicProfileRequest\x1a\x1b.user.v1.PublicProfileReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/user/profile\x12k\n" +
	"\x0fUpdateMyProfile\x12\x1f.user.v1.UpdateMyProfileRequest\x1a\x13.user.v1.EmptyReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/auth/my/profile/updateB<Z:codeup.aliyun.com/qimao/blog/ai-blog/backend/api/user;userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_user_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: user.v1.RegisterRequest
	(*GetMyProfileRequest)(nil),     // 1: user.v1.GetMyProfileRequest
	(*GetPublicProfileRequest)(nil), // 2: user.v1.GetPublicProfileRequest
	(*UpdateMyProfileRequest)(nil),  // 3: user.v1.UpdateMyProfileRequest
	(*EmptyReply)(nil),              // 4: user.v1.EmptyReply
	(*ProfileReply)(nil),            // 5: user.v1.ProfileReply
	(*PublicProfileReply)(nil),      // 6: user.v1.PublicProfileReply
}
var file_user_user_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.Register:input_type -> user.v1.RegisterRequest
	1, // 1: user.v1.UserService.GetMyProfile:input_type -> user.v1.GetMyProfileRequest
	2, // 2: user.v1.UserService.GetPublicProfile:input_type -> user.v1.GetPublicProfileRequest
	3, // 3: user.v1.UserService.UpdateMyProfile:input_type -> user.v1.UpdateMyProfileRequest
	4, // 4: user.v1.UserService.Register:output_type -> user.v1.EmptyReply
	5, // 5: user.v1.UserService.GetMyProfile:output_type -> user.v1.ProfileReply
	6, // 6: user.v1.UserService.GetPublicProfile:output_type -> user.v1.PublicProfileReply
	4, // 7: user.v1.UserService.UpdateMyProfile:output_type -> user.v1.EmptyReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
