// Code generated by protoc-gen-gin-http. DO NOT EDIT.
// versions:
// - protoc-gen-gin-http v0.0.6
// - protoc             v7.35.1
// source: user/user.proto

package user

import (
	bytes "bytes"
	log "codeup.aliyun.com/qimao/leo/leo/log"
	code_encoding "codeup.aliyun.com/qimao/leo/lib/code-encoding"
	form "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	errassets "codeup.aliyun.com/qimao/leo/lib/errassets"
	json "codeup.aliyun.com/qimao/leo/lib/pkg/json"
	render "codeup.aliyun.com/qimao/leo/lib/render"
	gin "github.com/gin-gonic/gin"
	io "io"
	http "net/http"
)

import (
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/json"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/proto"
)

// 引入指定包
var _ = new(gin.Context)
var _ = new(bytes.Buffer)
var _ = code_encoding.Version
var _ = http.StatusOK
var _ = errassets.LevelToast
var _ = log.LevelDebug
var _ = io.EOF
var _ = json.Marshal
var _ = form.Name

// 单纯引入 render 包，后续render 包加个常量
// var _, _  = render.render.JSON(0,0)

type UserServiceResponse struct {
	Data any `json:"data"`
}

const OperationUserServiceChangePassword = "/user.v1.UserService/ChangePassword"
const OperationUserServiceConfirmAvatar = "/user.v1.UserService/ConfirmAvatar"
const OperationUserServiceGetAvatarUploadURL = "/user.v1.UserService/GetAvatarUploadURL"
const OperationUserServiceGetMyProfile = "/user.v1.UserService/GetMyProfile"
const OperationUserServiceGetPublicProfile = "/user.v1.UserService/GetPublicProfile"
const OperationUserServiceLogin = "/user.v1.UserService/Login"
const OperationUserServiceLogout = "/user.v1.UserService/Logout"
const OperationUserServiceRegister = "/user.v1.UserService/Register"
const OperationUserServiceUpdateMyAccount = "/user.v1.UserService/UpdateMyAccount"
const OperationUserServiceUpdateMyProfile = "/user.v1.UserService/UpdateMyProfile"
const OperationUserServiceVerifyOldPassword = "/user.v1.UserService/VerifyOldPassword"

type UserServiceHTTPServerController interface {
	ChangePassword(*gin.Context, *ChangePasswordRequest) (*EmptyReply, error)
	ConfirmAvatar(*gin.Context, *ConfirmAvatarRequest) (*AvatarUploadReply, error)
	GetAvatarUploadURL(*gin.Context, *GetAvatarUploadURLRequest) (*AvatarUploadReply, error)
	GetMyProfile(*gin.Context, *GetMyProfileRequest) (*ProfileReply, error)
	GetPublicProfile(*gin.Context, *GetPublicProfileRequest) (*PublicProfileReply, error)
	Login(*gin.Context, *LoginRequest) (*LoginReply, error)
	Logout(*gin.Context, *LogoutRequest) (*EmptyReply, error)
	Register(*gin.Context, *RegisterRequest) (*EmptyReply, error)
	UpdateMyAccount(*gin.Context, *UpdateMyAccountRequest) (*EmptyReply, error)
	UpdateMyProfile(*gin.Context, *UpdateMyProfileRequest) (*EmptyReply, error)
	VerifyOldPassword(*gin.Context, *VerifyOldPasswordRequest) (*PasswordChangeTokenReply, error)
}

func RegisterUserServiceHTTPServerController(router *gin.RouterGroup, srv UserServiceHTTPServerController) {
	router.POST("/user/register", _UserService_Register0_HTTP_Handler(srv))
	router.POST("/user/login", _UserService_Login0_HTTP_Handler(srv))
	router.POST("/auth/my/logout", _UserService_Logout0_HTTP_Handler(srv))
	router.GET("/auth/my/profile", _UserService_GetMyProfile0_HTTP_Handler(srv))
	router.GET("/user/profile", _UserService_GetPublicProfile0_HTTP_Handler(srv))
	router.POST("/auth/my/profile/update", _UserService_UpdateMyProfile0_HTTP_Handler(srv))
	router.POST("/auth/my/password/verify", _UserService_VerifyOldPassword0_HTTP_Handler(srv))
	router.POST("/auth/my/password/change", _UserService_ChangePassword0_HTTP_Handler(srv))
	router.POST("/auth/my/account/update", _UserService_UpdateMyAccount0_HTTP_Handler(srv))
	router.POST("/auth/my/avatar/upload-url", _UserService_GetAvatarUploadURL0_HTTP_Handler(srv))
	router.POST("/auth/my/avatar/confirm", _UserService_ConfirmAvatar0_HTTP_Handler(srv))
}

func _UserService_Register0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RegisterRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.Register(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/Register err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/Register err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_Login0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in LoginRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.Login(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/Login err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/Login err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_Logout0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in LogoutRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.Logout(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/Logout err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/Logout err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_GetMyProfile0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetMyProfileRequest
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.GetMyProfile(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/GetMyProfile err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/GetMyProfile err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_GetPublicProfile0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetPublicProfileRequest
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.GetPublicProfile(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/GetPublicProfile err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/GetPublicProfile err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_UpdateMyProfile0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateMyProfileRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.UpdateMyProfile(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/UpdateMyProfile err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/UpdateMyProfile err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_VerifyOldPassword0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in VerifyOldPasswordRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.VerifyOldPassword(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/VerifyOldPassword err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/VerifyOldPassword err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_ChangePassword0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ChangePasswordRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.ChangePassword(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/ChangePassword err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/ChangePassword err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_UpdateMyAccount0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateMyAccountRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.UpdateMyAccount(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/UpdateMyAccount err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/UpdateMyAccount err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_GetAvatarUploadURL0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetAvatarUploadURLRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.GetAvatarUploadURL(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/GetAvatarUploadURL err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/GetAvatarUploadURL err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _UserService_ConfirmAvatar0_HTTP_Handler(srv UserServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ConfirmAvatarRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.ConfirmAvatar(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/user.v1.UserService/ConfirmAvatar err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := UserServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/user.v1.UserService/ConfirmAvatar err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}
