// Code generated by protoc-gen-gin-http. DO NOT EDIT.
// versions:
// - protoc-gen-gin-http v0.0.6
// - protoc             v7.35.1
// source: comment/comment.proto

package comment

import (
	bytes "bytes"
	log "codeup.aliyun.com/qimao/leo/leo/log"
	code_encoding "codeup.aliyun.com/qimao/leo/lib/code-encoding"
	form "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	errassets "codeup.aliyun.com/qimao/leo/lib/errassets"
	json "codeup.aliyun.com/qimao/leo/lib/pkg/json"
	render "codeup.aliyun.com/qimao/leo/lib/render"
	gin "github.com/gin-gonic/gin"
	io "io"
	http "net/http"
)

import (
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/form"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/json"
	_ "codeup.aliyun.com/qimao/leo/lib/code-encoding/proto"
)

// 引入指定包
var _ = new(gin.Context)
var _ = new(bytes.Buffer)
var _ = code_encoding.Version
var _ = http.StatusOK
var _ = errassets.LevelToast
var _ = log.LevelDebug
var _ = io.EOF
var _ = json.Marshal
var _ = form.Name

// 单纯引入 render 包，后续render 包加个常量
// var _, _  = render.render.JSON(0,0)

type CommentServiceResponse struct {
	Data any `json:"data"`
}

const OperationCommentServiceCreateComment = "/comment.v1.CommentService/CreateComment"
const OperationCommentServiceListReplies = "/comment.v1.CommentService/ListReplies"
const OperationCommentServiceListRootComments = "/comment.v1.CommentService/ListRootComments"

type CommentServiceHTTPServerController interface {
	CreateComment(*gin.Context, *CreateCommentRequest) (*CreateCommentReply, error)
	ListReplies(*gin.Context, *ReplyListRequest) (*CommentListReply, error)
	ListRootComments(*gin.Context, *RootCommentListRequest) (*CommentListReply, error)
}

func RegisterCommentServiceHTTPServerController(router *gin.RouterGroup, srv CommentServiceHTTPServerController) {
	router.POST("/auth/comment/create", _CommentService_CreateComment0_HTTP_Handler(srv))
	router.GET("/comment/list/roots", _CommentService_ListRootComments0_HTTP_Handler(srv))
	router.GET("/comment/list/replies", _CommentService_ListReplies0_HTTP_Handler(srv))
}

func _CommentService_CreateComment0_HTTP_Handler(srv CommentServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateCommentRequest
		data, err := io.ReadAll(c.Request.Body)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		if len(data) != 0 {
			codec, _ := code_encoding.CodecForRequest(c.Request, "Content-Type")
			if err = codec.Unmarshal(data, &in); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
				return
			}
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.CreateComment(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/comment.v1.CommentService/CreateComment err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := CommentServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/comment.v1.CommentService/CreateComment err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _CommentService_ListRootComments0_HTTP_Handler(srv CommentServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RootCommentListRequest
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.ListRootComments(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/comment.v1.CommentService/ListRootComments err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := CommentServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/comment.v1.CommentService/ListRootComments err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}

func _CommentService_ListReplies0_HTTP_Handler(srv CommentServiceHTTPServerController) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ReplyListRequest
		if err := code_encoding.GetCodec(form.Name).Unmarshal([]byte(c.Request.URL.Query().Encode()), &in); err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, "请求参数错误")))
			return
		}
		var j interface{} = &in
		if v, ok := j.(validator); ok {
			if err := v.Validate(); err != nil {
				c.Negotiate(render.AbortWithError(c, errassets.NewError(44010102, err.Error())))
				return
			}
		}
		out, err := srv.ListReplies(c, &in)
		if err != nil {
			// 兼容来的err code 方式
			if _, ok := err.(errassets.ErrorNo); ok {
				c.Negotiate(render.AbortWithError(c, err.(errassets.ErrorNo)))
				return
			}
			log.Error("/comment.v1.CommentService/ListReplies err: ", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		obj := CommentServiceResponse{
			Data: out,
		}
		b, err := json.Marshal(obj)
		if err != nil {
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		c.Writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, err = c.Writer.Write(b)
		if err != nil {
			log.Errorf("/comment.v1.CommentService/ListReplies err: %+v", err)
			c.Negotiate(render.AbortWithError(c, errassets.NewError(47010101, "系统繁忙，请稍后再试")))
			return
		}
		return
	}
}
