package entity

type Book struct {
	Id                     uint
	Title                  string
	AliasTitle             string
	StacksBookId           uint
	SourceId               uint
	ApiBookId              uint64
	WordsNum               uint
	Author                 string
	AuthorId               uint
	Characters             string
	IsOver                 uint8
	Category1              uint
	Category2              uint
	ImageLink              string
	LatestChapterId        uint64
	LatestChapterTitle     string
	LatestChapterUrl       string
	TotalChapterNum        int16
	OrderNum               uint
	RankWeek               uint
	RankMonth              uint
	ChapterVer             uint
	ChapterTitleFormat     uint8
	IsBreak                uint8
	IsLock                 uint8
	IsClassical            uint8
	IsUp                   uint8
	IsWhite                uint8
	UpdateTime             int
	Status                 uint16
	SubTreasury            uint16
	SubTreasuryTime        uint
	CreatedAt              uint
	UpdatedAt              uint
	UpTime                 uint
	Level                  uint16
	Level2                 uint16
	IsTest                 uint16
	SensitiveType          uint16
	Score                  float32
	Score2                 float32
	InitScore              float32
	Count                  uint
	DominantHue            string
	EachAudit              uint8
	Price                  float32
	IsHidden               uint8
	LatestChapterUpdatedAt int
	CurrentFlowPool        uint16
	CurrentFlowPoolTime    uint
	RightFlowPool          uint16
	RewardStatus           uint16
	LevelNew               uint
	LevelPotential         uint
	LevelPublish           uint
	LevelPublishPotential  uint
}
